### ISSUE TITLE
大佬求个acg-faka插件

### ISSUE THREAD

**Issue by zyz1123** [LightCountry/TokenPay#10]
独角数卡这些都有了。求个acg-faka插件

**Comment by moshaoli688** [comment]
我是通过易支付支持了acg-faka

**Comment by ZhangYiQiu** [comment]
易支付中转吧

**Comment by Rockney99** [comment]
> 易支付中转吧

acg-faka和dujiaofaka有点区别 我使用dujiaofaka易支付的QQ钱包通道中转实现中转收U但是acg-faka的易支付配置只能填一个商户
![image](https://github.com/LightCountry/TokenPay/assets/42824224/2ce12897-df2f-45f8-887b-3acb23893d08)
![image](https://github.com/LightCountry/TokenPay/assets/42824224/708cd2b1-2b3c-41be-a5cc-2bedc173d38d)
