### ISSUE TITLE
生成的二维码添加钱包地址，防止被篡改

### ISSUE THREAD

**Issue by fivepe** [LightCountry/TokenPay#12]
文本格式的钱包地址容易被篡改，返回的二维码能否在底部添加下收款地址，防止被恶意软件修改地址，以起到提示用户作用。
类如
![image](https://github.com/LightCountry/TokenPay/assets/131561603/f7a030ac-0318-41b2-a0da-b681629ff4fd)

**Comment by ZhangYiQiu** [comment]
你自己对接api的话，可以自己在html上增加地址显示，接口返回的就仅仅是地址的二维码
