### ISSUE TITLE
大佬，添加不了USDP和BUSD

### ISSUE THREAD

**Issue by xiaoyawl** [LightCountry/TokenPay#14]
{
      //"Enable": false,
      "Enable": true,
      "ChainName": "以太坊",
      "ChainNameEN": "ETH",
      "BaseCoin": "ETH",
      "Decimals": 18,
      "ScanHost": "https://etherscan.io",
      "ApiHost": "https://api.etherscan.io",
      "ApiKey": "XXXXXXXXXXXXXXXXXXXXXXXXXX", // 此处申请 https://etherscan.io/myapikey
      "ERC20Name": "ERC20",
      "ERC20": [
        {
          "Name": "USDT", // 代币名称
          "ContractAddress": "0xdAC17F958D2ee523a2206206994597C13D831ec7" //合约地址
        },
        {
          "Name": "USDC", // 代币名称
          "ContractAddress": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48" //合约地址
        },
        {
          "Name": "TUSD", // 代币名称
          "ContractAddress": "0x0000000000085d4780B73119b644AE5ecd22b376" //合约地址
        },
        {
          "Name": "USDP", // 代币名称
          "ContractAddress": "0x8e870d67f660d95d5be530380d0ec0bd388289e1" //合约地址
        },
        {
          "Name": "BUSD", // 代币名称
          "ContractAddress": "0x4Fabb145d64652a948d72533023f6E7A623C7C53" //合约地址
        }
      ]
    },

<img width="535" alt="2023-06-16_08-26-27" src="https://github.com/LightCountry/TokenPay/assets/2193977/6d7fda38-9611-43f3-a2f8-0e193efba365">

**Comment by yesuter** [comment]
<img width="715" alt="image" src="https://github.com/LightCountry/TokenPay/assets/140046919/b89b1b12-08d2-426b-ba0a-0477c2b6aa50">
为什么我只更新两个汇率...纠结...

**Comment by ninetian** [comment]
> <img alt="image" width="715" src="https://user-images.githubusercontent.com/140046919/254797030-b89b1b12-08d2-426b-ba0a-0477c2b6aa50.png"> 为什么我只更新两个汇率...纠结...

appsettings.json里定义币种就可以了
`json
  "Rate": { //汇率 设置0将使用自动汇率
    "BNB": 0,
    "TRX": 0,
    "ETH": 0,
    "USDT": 0,
    "USDC": 0,
    "MATIC": 0,
  },
`

**Comment by ninetian** [comment]
> 

可能加错地方了，BUSD应该是是币安智能链吧，加到BSC那里面试试

```json
    {
      "Enable": false,
      "ChainName": "币安智能链",
      "ChainNameEN": "BSC",
      "BaseCoin": "BNB",
      "Decimals": 18,
      "ScanHost": "https://www.bscscan.com",
      "ApiHost": "https://api.bscscan.com",
      "ApiKey": "", // 此处申请 https://bscscan.com/myapikey
      "ERC20Name": "BEP20",
      "ERC20": [
        {
          "Name": "USDT",
          "ContractAddress": "0x55d398326f99059ff775485246999027b3197955"
        },
        {
          "Name": "USDC",
          "ContractAddress": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"
        },
	{
		"Name": "BUSD", // 代币名称
		"ContractAddress": "0x4Fabb145d64652a948d72533023f6E7A623C7C53" //合约地址
	}
      ]
    },
```

它汇率调用的OKX的接口，如果还是一样提示 ，可能代表OKX没这个币种，或者使用的OKX接口不是最新版

**Comment by ZhangYiQiu** [comment]
汇率查询使用的是OKX的汇率，如果OKX没有该币种，获取汇率将会失败，你可以在配置文件中手动指定汇率
