### ISSUE TITLE
无法支付Polygon USDT

### ISSUE THREAD

**Issue by monlor** [LightCountry/TokenPay#16]
Failed to create order. Error: 不支持的币种【EVM_POLYGON_USDT_ERC20】！ 当前支持的币种参数有：TRX, USDT_TRC20

已经配置了EVM和TRON的收款地址

**Comment by ninetian** [comment]
修改

appsettings.josn

添加  原生币种 MATIC 

```json
  "Rate": { //汇率 设置0将使用自动汇率
    "BNB": 0,
    "TRX": 0,
    "ETH": 0,
    "USDT": 0,
    "USDC": 0,
    "MATIC": 0,
  },
```

evmchains.json 配置链   enable 设置为 true  开启， 申请个API KEY写好
```json
    {
      "Enable": false,
      "ChainName": "Polygon",
      "ChainNameEN": "Polygon",
      "BaseCoin": "MATIC",
      "Decimals": 18,
      "ScanHost": "https://polygonscan.com",
      "ApiHost": "https://api.polygonscan.com",
      "ApiKey": "", // 此处申请 https://polygonscan.com/myapikey
      "ERC20Name": "ERC20",
      "ERC20": [
        {
          "Name": "USDT",
          "ContractAddress": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
        },
        {
          "Name": "USDC",
          "ContractAddress": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
        }
      ]
    }

```

变量
EVM_Polygon_MATIC
EVM_Polygon_USDT_ERC20
EVM_Polygon_USDC_ERC20

测下，应该就可以

**Comment by ninetian** [comment]
因为后来没用过这    
我记忆里 是 **Polygon**  ，不是大写 **POLYGON**    
    你试试

**Comment by monlor** [comment]
还是提示这个`Failed to create order. Error: 不支持的币种【EVM_Polygon_USDT_ERC20】！ 当前支持的币种参数有：TRX, USDT_TRC20`
我的配置`appsettings.json`
```
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "DB": "Data Source=/data/TokenPay.db; Pooling=true;"
  },
  "TRON-PRO-API-KEY": "xxx", // 避免接口请求频繁被限制，此处申请 https://www.trongrid.io/dashboard/keys
  "BaseCurrency": "CNY", //默认货币，支持 CNY、USD、EUR、GBP、AUD、HKD、TWD、SGD
  "Rate": { //汇率 设置0将使用自动汇率
    "USDT": 0,
    "TRX": 0,
    "ETH": 0,
    "USDC": 0,
    "MATIC": 0,
  },
  "ExpireTime": 1800, //单位秒
  "UseDynamicAddress": false, //是否使用动态地址，设为false时，与EPUSDT表现类似；设为true时，为每个下单用户分配单独的收款地址
  "Address": { // UseDynamicAddress设为false时在此配置TRON收款地址，EVM可以替代所有ETH系列的收款地址，支持单独配置某条链的收款地址
    "TRON": [ "xxx" ]
  },
  "OnlyConfirmed": false, //默认仅查询已确认的数据，如果想要回调更快，可以设置为false
  "NotifyTimeOut": 3, //异步通知超时时间
  "ApiToken": "xxx", //异步通知密钥，请务必修改此密钥为随机字符串，脸滚键盘即可
  "WebSiteUrl": "https://tokenpay.xxx.com", //配置服务器外网域名
  "Telegram": {
    "AdminUserId": 123, // 你的账号ID，如不知道ID，可给https://t.me/EShopFakaBot 发送 /me 获取用户ID
    "BotToken": "xxx" //从https://t.me/BotFather 创建机器人时，会给你BotToken
  }
```
evmchains.json
```
{
  "EVMChains": [
    {
      "Enable": false,
      "ChainName": "以太坊",
      "ChainNameEN": "ETH",
      "BaseCoin": "ETH",
      "Decimals": 18,
      "ScanHost": "https://etherscan.io",
      "ApiHost": "https://api.etherscan.io",
      "ApiKey": "", // 此处申请 https://etherscan.io/myapikey
      "ERC20Name": "ERC20",
      "ERC20": [
        {
          "Name": "USDT",
          "ContractAddress": ""
        }
      ]
    },
    {
      "Enable": false,
      "ChainName": "币安智能链",
      "ChainNameEN": "BSC",
      "BaseCoin": "BNB",
      "Decimals": 18,
      "ScanHost": "https://www.bscscan.com",
      "ApiHost": "https://api.bscscan.com",
      "ApiKey": "", // 此处申请 https://bscscan.com/myapikey
      "ERC20Name": "BEP20",
      "ERC20": [
        {
          "Name": "USDT",
          "ContractAddress": ""
        }
      ]
    },
    {
      "Enable": true,
      "ChainName": "Polygon",
      "ChainNameEN": "Polygon",
      "BaseCoin": "MATIC",
      "Decimals": 18,
      "ScanHost": "https://polygonscan.com",
      "ApiHost": "https://api.polygonscan.com",
      "ApiKey": "xxx", // 此处申请 https://polygonscan.com/myapikey
      "ERC20Name": "ERC20",
      "ERC20": [
        {
          "Name": "USDT",
          "ContractAddress": "xxx"
        }
      ]
    }
  ]
}
```

**Comment by monlor** [comment]
后台日志有报错，MATIC汇率没有显示出来
<img width="1307" alt="image" src="https://github.com/LightCountry/TokenPay/assets/20394007/6bab0710-98b6-4460-b406-c13184edcfd5">

**Comment by ninetian** [comment]
程序使用最新的
然后使用境外VPS测试，这东西依赖的是公共URL，有些ISP不稳定

另外你是不是搞错方向了?
确认错误是TOKENPAY返回的?
是不是你写插件对接TOKENPAY , 插件的问题 例如 易支付或者什么发卡程序  例如因为易支付没更新币种数据导致?

**Comment by monlor** [comment]
哦，对，可能是支付插件限制了支持的币种，我看看

**Comment by ninetian** [comment]
还又个问题
你给出的 appsettings.json 
那个 EVM地址呢?  你配置了吗?

```json

  "Address": { // UseDynamicAddress设为false时在此配置TRON收款地址，EVM可以替代所有ETH系列的收款地址，支持单独配置某条链的收款地址
    "TRON": [ "xxx" ]
  },

```
不是应该是? 

```json
  "Address": { // UseDynamicAddress设为false时在此配置TRON收款地址，EVM可以替代所有ETH系列的收款地址，支持单独配置某条链的收款地址
    "TRON": [ "xxx" ],
    "EVM": ["这里你ETH地址呢?"]
  },

```

**Comment by monlor** [comment]
在evmchains里配置了对应链的收款地址，还需要EVM地址是做什么呢

**Comment by ninetian** [comment]
晕，我看了下你这docker，你都没理解ETH网络。。。。。

```json

收款地址 是配置这里  "Address": { // UseDynamicAddress设为false时在此配置TRON收款地址，EVM可以替代所有ETH系列的收款地址，支持单独配置某条链的收款地址
    "TRON": [ "xxx" ],
    "EVM": ["这里你ETH收款地址"]
  },

```

EVM链接里的那个是 合约地址  你放了收款地址。。。。。

简单理解就是 ETH是央行，给你一个固定银行账户
其他的例如泰达币是消费银行，它发行USDT币种 合约地址可以理解为类似银行路由号
你收到的USDT 是 在ETH网络里 根据合约地址转换的

可以参考下这个扩展币种的文档
https://doc.whmcscn.com/web/#/5/31

**Comment by monlor** [comment]
哦哦，我确实没太搞懂😂，是不是每个币种的合约地址都是固定的

**Comment by ninetian** [comment]
可以参考下这个扩展币种的文档
https://doc.whmcscn.com/web/#/5/31

有写，都是固定的

**Comment by monlor** [comment]
还是不行，不支持币种的错应该是TokenPay报的吧，我用独角数卡的插件也报错
<img width="754" alt="image" src="https://github.com/LightCountry/TokenPay/assets/20394007/927cd44f-2a0e-4518-99cb-b9065f6ddd63">
```
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "DB": "Data Source=/data/TokenPay.db; Pooling=true;"
  },
  "TRON-PRO-API-KEY": "xxx", // 避免接口请求频繁被限制，此处申请 https://www.trongrid.io/dashboard/keys
  "BaseCurrency": "CNY", //默认货币，支持 CNY、USD、EUR、GBP、AUD、HKD、TWD、SGD
  "Rate": { //汇率 设置0将使用自动汇率
    "USDT": 0,
    "TRX": 0,
    "ETH": 0,
    "USDC": 0,
    "MATIC": 0
  },
  "ExpireTime": 1800, //单位秒
  "UseDynamicAddress": false, //是否使用动态地址，设为false时，与EPUSDT表现类似；设为true时，为每个下单用户分配单独的收款地址
  "Address": { // UseDynamicAddress设为false时在此配置TRON收款地址，EVM可以替代所有ETH系列的收款地址，支持单独配置某条链的收款地址
    "TRON": [ "xxx" ],
    "EVM": [ "xxx" ]
  },
  "OnlyConfirmed": false, //默认仅查询已确认的数据，如果想要回调更快，可以设置为false
  "NotifyTimeOut": 3, //异步通知超时时间
  "ApiToken": "xxx", //异步通知密钥，请务必修改此密钥为随机字符串，脸滚键盘即可
  "WebSiteUrl": "https://tokenpay.xxx.com", //配置服务器外网域名
  "Telegram": {
    "AdminUserId": xxx, // 你的账号ID，如不知道ID，可给https://t.me/EShopFakaBot 发送 /me 获取用户ID
    "BotToken": "xxx" //从https://t.me/BotFather 创建机器人时，会给你BotToken
  }
}
```
{
  "EVMChains": [
    {
      "Enable": false,
      "ChainName": "以太坊",
      "ChainNameEN": "ETH",
      "BaseCoin": "ETH",
      "Decimals": 18,
      "ScanHost": "https://etherscan.io",
      "ApiHost": "https://api.etherscan.io",
      "ApiKey": "", // 此处申请 https://etherscan.io/myapikey
      "ERC20Name": "ERC20",
      "ERC20": [
        {
          "Name": "USDT",
          "ContractAddress": "0xdAC17F958D2ee523a2206206994597C13D831ec7"
        },
        {
          "Name": "USDC",
          "ContractAddress": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
        }
      ]
    },
    {
      "Enable": false,
      "ChainName": "币安智能链",
      "ChainNameEN": "BSC",
      "BaseCoin": "BNB",
      "Decimals": 18,
      "ScanHost": "https://www.bscscan.com",
      "ApiHost": "https://api.bscscan.com",
      "ApiKey": "", // 此处申请 https://bscscan.com/myapikey
      "ERC20Name": "BEP20",
      "ERC20": [
        {
          "Name": "USDT",
          "ContractAddress": "0x55d398326f99059ff775485246999027b3197955"
        },
        {
          "Name": "USDC",
          "ContractAddress": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"
        }
      ]
    },
    {
      "Enable": true,
      "ChainName": "Polygon",
      "ChainNameEN": "Polygon",
      "BaseCoin": "MATIC",
      "Decimals": 18,
      "ScanHost": "https://polygonscan.com",
      "ApiHost": "https://api.polygonscan.com",
      "ApiKey": "xxx", // 此处申请 https://polygonscan.com/myapikey
      "ERC20Name": "ERC20",
      "ERC20": [
        {
          "Name": "USDT",
          "ContractAddress": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
        },
        {
          "Name": "USDC",
          "ContractAddress": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
        }
      ]
    }
  ]
}
```

```

**Comment by monlor** [comment]
后台日志
<img width="1302" alt="image" src="https://github.com/LightCountry/TokenPay/assets/20394007/0c053616-e4f7-4919-8ac3-c7a8ee1f65a4">

**Comment by monlor** [comment]
独角数卡的插件配置用仓库中的sql脚本插入的，我只改了密钥和tokenpay服务地址

**Comment by ZhangYiQiu** [comment]
`evmchains.json`的文件名大小写不要改，正确的应该是`EVMChains.json`，修改`EVMChains.json`之后也要重启TokenPay

**Comment by monlor** [comment]
换成大写还是报错，应该是tokenpay服务返回的错误
`支付网关异常！不支持的币种【EVM_POLYGON_USDT_ERC20】！ 当前支持的币种参数有：TRX, USDT_TRC20`

**Comment by ZhangYiQiu** [comment]
你截图TokenPay文件列表我看看

**Comment by monlor** [comment]
<img width="894" alt="image" src="https://github.com/LightCountry/TokenPay/assets/20394007/93cc18f6-2e1d-4625-b7d7-3edf03b1aa09">

**Comment by ZhangYiQiu** [comment]
截图这个文件的Polygon部分

**Comment by ZhangYiQiu** [comment]
![image](https://github.com/LightCountry/TokenPay/assets/22910338/9c8eb07d-3892-4272-9121-327d7112a149)

**Comment by monlor** [comment]
不好意思，太久了，刚才没有配置Polygon的API信息。现在是可以了，之前应该就是EVMChain大小写的问题，感谢！
