### ISSUE TITLE
端口监听IP修改

### ISSUE THREAD

**Issue by monlor** [LightCountry/TokenPay#19]
服务默认监听ip为127.0.0.1，这个有办法修改么，看了官方文档没找到相关配置。

**Comment by ZhangYiQiu** [comment]
不建议修改，使用nginx或者apache之类的配置反向代理

**Comment by monlor** [comment]
我是使用docker部署，反向代理使用`nginx-proxy/nginx-proxy-manager`等容器实现，容器里面如果再加一层反向代理感觉意义不大
https://github.com/monlor/dockerfiles/tree/main/tokenpay

**Comment by ZhangYiQiu** [comment]
你都用docker了，映射一下端口不就可以访问了

**Comment by monlor** [comment]
监听到127.0.0.1的端口，映射不了

**Comment by ZhangYiQiu** [comment]
docker里启动默认应该是监听0.0.0.0:80

**Comment by monlor** [comment]
你们程序能识别docker环境运行么？我试过了还是监听127.0.0.1:5000

**Comment by ZhangYiQiu** [comment]
docker启动会是这个日志
[12:21:21 INF] Now listening on: http://[::]:80

**Comment by monlor** [comment]
你们有docker镜像么？怎样启动能实现监听80

**Comment by ZhangYiQiu** [comment]
目录下不就有dockerfile?

**Comment by monlor** [comment]
好的，不过还是希望appsettings.json能添加关于端口监听的相关配置，修改起来也方便些

**Comment by hiouttime** [comment]
因程序没有对 asp.net 服务器做什么改动，appsetting.json 能够直接支持修改：

```json
  "Kestrel": {
    "EndPoints": {
      "Http": {
        "Url": "http://0.0.0.0:5000"
      }
    }
  },
```
