### ISSUE TITLE
支付已经返回ok，但是通知还是错误的，状态码是200

### ISSUE THREAD

**Issue by yangliu123** [LightCountry/TokenPay#20]
![image](https://github.com/LightCountry/TokenPay/assets/10783503/8854b2cb-aa67-4da1-9eff-d1c4b65d4e9e)
![image](https://github.com/LightCountry/TokenPay/assets/10783503/dd7887e0-0234-406b-b069-f4cbad3fbb15)
![image](https://github.com/LightCountry/TokenPay/assets/10783503/0a00cabb-a217-4d21-b175-6863b6a1b437)
这两个条件应该都满足，http的status都是200返回都是ok

**Comment by ZhangYiQiu** [comment]
确定返回的数据不带空格或者引号吗？

**Comment by yangliu123** [comment]
![image](https://github.com/LightCountry/TokenPay/assets/10783503/0887c54c-3fde-4b32-92b1-31f75b9264c9)
确实没有带空格和双引号

**Comment by ZhangYiQiu** [comment]
你把你的代码部署个测试api，搞个参数给我，我请求下试试

**Comment by yangliu123** [comment]
请求url: https://mh-api.tiktokvpn.xyz/tokenpay/notify_url
参数：{
    "ActualAmount": "0.1",
    "Amount": "0.1745",
    "BaseCurrency": "USD",
    "BlockChainName": "Polygon",
    "BlockTransactionId": "0xf2b7a84f4a7b6d9c9dc35850a816b1f24122281f59480bda417fc94c5aadc97a",
    "Currency": "EVM_Polygon_MATIC",
    "CurrencyName": "MATIC",
    "FromAddress": "0x290880cbd1c37bc7b85c6ccc50a1cb55811b244f",
    "Id": "64f9a083-d81b-2e70-0081-a1f2356f3ecb",
    "OrderUserKey": "2",
    "OutOrderId": "R20230907180554046672",
    "PayTime": "2023-09-07 10:07:39",
    "Signature": "06ddb00f8c5f0d7547799c580aae7b56",
    "Status": 1,
    "ToAddress": "0x0eD6Bb8aa389881F211AC9d12293F2328501bEC9"
}

**Comment by ZhangYiQiu** [comment]
![image](https://github.com/LightCountry/TokenPay/assets/22910338/ced2339b-9cec-4bc6-a5f8-6d64b28063a8)
这很明显了吧

**Comment by yangliu123** [comment]
这是java字符返回的，根本没有办法处理，它的字符串就是这样子

**Comment by yangliu123** [comment]
![image](https://github.com/LightCountry/TokenPay/assets/10783503/47f4c1b0-a698-457e-a7bb-f376ed81c543)

**Comment by ZhangYiQiu** [comment]
> 这是java字符返回的，根本没有办法处理，它的字符串就是这样子

可能是你用的框架处理的，如果对字符串进行json序列化，就会成这样子

**Comment by ZhangYiQiu** [comment]
你用的什么框架？

**Comment by yangliu123** [comment]
那个mall开源框架改的

**Comment by yangliu123** [comment]
有可能，我去瞅瞅序列化逻辑

**Comment by yangliu123** [comment]
还有一个问题，请教，我修改完页面，这个咋打包

**Comment by ZhangYiQiu** [comment]
> 还有一个问题，请教，我修改完页面，这个咋打包

你可以搜索一下.net6发布教程

**Comment by yangliu123** [comment]
好的，谢谢，有没有erc打赏地址给一个

**Comment by ZhangYiQiu** [comment]
> 好的，谢谢，有没有erc打赏地址给一个

0x11eb6770bcc6bbd6e52bc15be0f051ded60cdbec
