### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by sixgodfan** [LightCountry/TokenPay#25]
TRON(usdt/trx)、ETH(eth/usdt/usdc)、BSC(bnb/eth/usdt/usdc)地址余额监控，设置单个地址余额阈值达到多少自动归集到某个地址去。成千上万个地址的批量查余额，一键转账，自动归集。授权转账。
支持一键上传多个私钥、助记词，根据私钥、助记词自动生成TRON和ETH地址，并“实时”监控地址相关网络余额，余额大于多少自动归集，如有余额地址没有能量bnb或者trx等手续费没法转账则自动转入能量、bnb或者trx（已设置好相关手续费地址私钥）来转账归集。谢谢！

**Comment by ZhangYiQiu** [comment]
> 这是开源项目，不是许愿池😂。

而且你说的这些只有在使用动态地址的情况下才能实现，据我了解，目前使用本项目的大部分用户大多使用静态地址。
