### ISSUE TITLE
如果想添加币安链的代币收款，请问如何处理配置呢 ？

### ISSUE THREAD

**Issue by douyaolai** [LightCountry/TokenPay#27]
如果想添加币安链的代币收款，请问如何处理配置呢 ？

**Comment by douyaolai** [comment]
这样设置可以不 ？
![20240302150405](https://github.com/LightCountry/TokenPay/assets/21256502/be1481b3-0e06-47a9-a55b-030c40dab395)

**Comment by ninetian** [comment]
参考 https://doc.whmcscn.com/web/#/5/31

**Comment by douyaolai** [comment]
> 参考 https://doc.whmcscn.com/web/#/5/31

好的，我研究下，感谢！

**Comment by ZhangYiQiu** [comment]
对的
