### ISSUE TITLE
tokenpay 支持  https://arbiscan.io

### ISSUE THREAD

**Issue by douyaolai** [LightCountry/TokenPay#30]
tokenpay 应该也支持  https://arbiscan.io/ 吧

**Comment by ZhangYiQiu** [comment]
应该是支持的，你可以在 [EVMChains.json](https://github.com/LightCountry/TokenPay/blob/master/src/TokenPay/EVMChains.Example.json) 中增加此链的信息

**Comment by douyaolai** [comment]
> 应该是支持的，你可以在 [EVMChains.json](https://github.com/LightCountry/TokenPay/blob/master/src/TokenPay/EVMChains.Example.json) 中增加此链的信息

好的，我研究试试看

**Comment by toshiyu1998** [comment]
> > 应该是支持的，你可以在 [EVMChains.json](https://github.com/LightCountry/TokenPay/blob/master/src/TokenPay/EVMChains.Example.json) 中增加此链的信息
> 
> 好的，我研究试试看

大佬研究出来了吗
