### ISSUE TITLE
请问，如果配置USDT收款？

### ISSUE THREAD

**Issue by wuxiaol1981** [LightCountry/TokenPay#32]
按默认配置搭建好以后，是以TRON收款的。我想直接以USDT收款，需要怎么配置呢？

**Comment by douyaolai** [comment]
现有插件
[独角数卡插件](https://github.com/LightCountry/TokenPay/blob/master/Plugs/dujiaoka) | [独角数卡](https://github.com/assimon/dujiaoka) Github stars
[v2board插件](https://github.com/LightCountry/TokenPay/blob/master/Plugs/v2board) | [v2board](https://github.com/v2board/v2board) Github stars
[card-system插件](https://github.com/LightCountry/TokenPay/blob/master/Plugs/card-system) | [card-system](https://github.com/Tai7sy/card-system) Github stars
[彩虹易支付插件](https://github.com/LightCountry/TokenPay/blob/master/Plugs/epay) | [彩虹易支付官网](https://pay.cccyun.cc/)
[用户贡献的WHMCS插件](https://doc.whmcscn.com/web/#/5/30)，感谢 [@ninetian](https://github.com/ninetian) https://github.com/LightCountry/TokenPay/issues/13，使用者自行检查代码安全情况 | [WHMCS官网](https://www.whmcs.com/)

如果需要对接其他系统，则需要二开 。

**Comment by ZhangYiQiu** [comment]
USDT在TRON也有，默认配置启动就会支持TRX和USDT-TRC20两个币种，建议仔细阅读文档
