### ISSUE TITLE
内存占用不断增加，影响系统运行

### ISSUE THREAD

**Issue by wangegou** [LightCountry/TokenPay#34]
随着时间推移，tokenpay进程占用的内存会不断增加，从几百兆增加到几个G,非常可怕，希望大佬给优化一下

**Comment by ZhangYiQiu** [comment]
建议使用docker启动并限制使用的内存数量。

默认情况下，如果服务器空闲内存较多，.net默认会使用更多内存

**Comment by ZhangYiQiu** [comment]
可以尝试在程序目录下创建此文件，然后重启程序，这会加快程序的GC速度，看是否有所改善

`runtimeconfig.json`
```
{
  "runtimeOptions": {
   "configProperties": {
      "System.GC.Server": false,
      "System.GC.HeapCount": 12
   }
  }
}
```

**Comment by wangegou** [comment]
已经按照建议创建文件，但是没有得到改善，内存占用还会随着时间增长

**Comment by WuMe-sicx** [comment]
还是无法改善该问题,内存还是会长时间增加

**Comment by ZhangYiQiu** [comment]
将`runtimeconfig.json`改为`TokenPay.runtimeconfig.json`，然后重启下再观察下看看

**Comment by ZhangYiQiu** [comment]
好像直接加配置文件，配置项并没有生效，我重新打包一个，你们测试下 @wangegou @WuMe-sicx

**Comment by ZhangYiQiu** [comment]
尝试下这个版本 https://github.com/LightCountry/TokenPay/releases/tag/pre-v1.0.9-2024090901

**Comment by WuMe-sicx** [comment]
> 好像直接加配置文件，配置项并没有生效，我稍后重新打包一个包含这个配置项的包，你们测试下 @wangegou @WuMe-sicx

不知道是我问题还是心里作用 原本60占用 现在40了

**Comment by WuMe-sicx** [comment]
> 尝试下这个版本 https://github.com/LightCountry/TokenPay/releases/tag/pre-v1.0.9-2024090901

这个版本 内存占用低

**Comment by wangegou** [comment]
测试了，4个小时，基本稳定在146MB,这个版本确实优化了不少。


Mon Sep  9 05:05:25 PM CST 2024 - VmSize: 267882 MB, VmRSS: 122.312 MB
Mon Sep  9 05:05:30 PM CST 2024 - VmSize: 267882 MB, VmRSS: 122.461 MB
Mon Sep  9 05:05:35 PM CST 2024 - VmSize: 267882 MB, VmRSS: 122.492 MB
Mon Sep  9 05:05:40 PM CST 2024 - VmSize: 267882 MB, VmRSS: 122.492 MB
......
......
Mon Sep  9 08:24:36 PM CST 2024 - VmSize: 267953 MB, VmRSS: 145.91 MB
Mon Sep  9 08:24:41 PM CST 2024 - VmSize: 267953 MB, VmRSS: 145.91 MB
Mon Sep  9 08:24:46 PM CST 2024 - VmSize: 267953 MB, VmRSS: 145.91 MB
Mon Sep  9 08:24:51 PM CST 2024 - VmSize: 267953 MB, VmRSS: 145.91 MB

**Comment by ZhangYiQiu** [comment]
运行一天后如何？

**Comment by WuMe-sicx** [comment]
> 运行一天后如何？

1414061 root     /www/wwwuser/upay/TokenPay         0   215732   218045   227996 
TokenPay | 5.67%
该版本的优化确实不错 正式版的内存占用百分之20左右,该版本百分之5左右。
