### ISSUE TITLE
[Feature] 添加 User-Agent 支持

### ISSUE THREAD

**Issue by betaxab** [LightCountry/TokenPay#7]
您好，

希望添加 User-Agent 支持，由于目前的 UA 是空的，我的防火墙上设置了禁止空 UA 访问，所以无法通知到（从正常的角度来看，空 UA 怎么也不像是一个正常的程序）。

UA 格式可以是 TokenPay/$version 这样。

谢谢。

**Comment by ZhangYiQiu** [comment]
[已添加User-Agent支持](https://github.com/LightCountry/TokenPay/commit/bd05eb6b4d4b0c88dc96d6385c7b03e1c8eba3ce)
